### ISSUE TITLE
Allow disabling the logging bucket

### ISSUE THREAD

**Issue by jschaul** [cloudposse/terraform-aws-cloudfront-s3-cdn#24] opened 2018-07-27 10:49 UTC
Feature request:

I'd like to use the cdn module and have an option to not create a logging S3 bucket; i.e. not have [these 3 lines](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/main.tf#L114-L118)  and disable the [logging module](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/main.tf#L70-L83)

Is there a way to do this with a conditional flag (conditionals seem to be not well supported in terraform)? If not, is the only workaround a fork of your repo, deleting those parts?

Thanks!

**Comment by osterman** [comment] 2018-07-30 05:54
@jschaul typically we implement this by adding an `enabled` variable which disables the module. Not all of our modules support this flag. 

If you have time to implement this feature, we'll gladly accept the Pull Request.

Someone recently submitted this PR which demonstrates this strategy: https://github.com/cloudposse/terraform-aws-route53-alias/pull/11

We also have a module here that implements it: 
https://github.com/cloudposse/terraform-aws-ecs-cloudwatch-sns-alarms/

Please have a look. Also, join our slack team to reach us directly.

https://slack.cloudposse.com

**Comment by catdevman** [comment] 2018-10-20 19:49
@osterman If no one else is going to take this I am willing to take a look at it.  If I get it figured out I will put in a PR.  Love everything that CloudPosse is doing, especially for the Terraform community!

**Comment by catdevman** [comment] 2018-10-21 19:36
@osterman Still learning some of the tips and tricks of Terraform... Having some issues with optional adding the logging_config key for the aws_cloudfront_distribution resource.  So I added enabled to terraform-aws-s3-log-storage which is currently in PR, so I have it where it won't the logging s3 bucket.

The expected logging_config key :
```
logging_config {
  include_cookies = "${var.log_include_cookies}"
  bucket = "${module.logs.bucket_domain_name}"
  prefix = "${var.log_prefix}"
}
```

The issue is that bucket is required if you have the logging_config key there.

I am getting `"logging_config.0.bucket": required field is not set` error.

```
locals {
  logging_config       = "${var.is_logging_enabled == "true" ? join(",", list(map(
      "include_cookies", var.log_include_cookies,
      "bucket", module.logs.bucket_domain_name,
      "prefix", var.log_prefix
    ))) : join(",", list(""))}"
}

resource "aws_cloudfront_distribution" "default" {
  ...
  logging_config = ["${compact(split(",", local.logging_config))}"]
}
```

but if I do this it works fine without the values being in there:

```
resource "aws_cloudfront_distribution" "default" {
  ...
  logging_config = []
}
```

I am willing to continue to work on it but I was wondering if you have any tips for conditional list like this.  I was looking into overrides but before I spent my whole day trying to find a solution I thought it would be worth asking the community.

**Comment by osterman** [comment] 2018-10-21 19:50
@catdevman what you'll want to do is use the `join`+`splat` pattern. Here's an example: https://github.com/cloudposse/terraform-aws-dynamodb-autoscaler/pull/10/files#diff-7a370d8342e7203b805911c92454f0f4R100

**Comment by osterman** [comment] 2018-10-23 04:05
Ahk, you're right.

**Comment by catdevman** [comment] 2018-10-24 22:05
@osterman So I think this will all be fixed with Terraform 0.12 because of https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements.  What I didn't know is what your process was for determining what the minimum version of Terraform should be for a module.  I would hate to force people to upgrade if 0.12 just because of this feature but if it works for you it works for me.

**Comment by JMGVDEV** [comment] 2019-04-12 21:20
Hi there -- i'm facing this same issue, i need to disable creation of s3 logs bucket and logging feature for CloudFront

is there any workaround for this? 

Thanks for any suggestion/response

**Comment by gugacavalieri** [comment] 2019-11-05 13:07
Hey guys!

Any updates on this?

I will be happy to help :)

**Closed** 2020-01-22 17:40 UTC
Labels: enhancement, feature request, help wanted
