### ISSUE TITLE
Tests hyperlink on terraform module website is broken

### ISSUE THREAD

**Issue by Konig-Corey** [cloudposse/terraform-aws-cloudfront-s3-cdn#122] opened 2021-01-26 04:44 UTC
Super quick and simple. The "Tests" hyper link (https://registry.terraform.io/modules/cloudposse/cloudfront-s3-cdn/aws/test) is a broken link that is included on the readme for the module in Terraform Registry (registry.terraform.io)

Steps to repo: 
1: Goto `https://registry.terraform.io/modules/cloudposse/cloudfront-s3-cdn/aws/latest`
2: Look for sentence "For automated tests of the complete example using bats and Terratest (which tests and deploys the example on AWS), see test." 
3: Click the hyperlink "test"

**Comment by Nuru** [comment] 2021-05-13 03:28
@osterman @aknysh Where is that link supposed to take you? I can't tell if we should fix the link or just delete it.

**Comment by nitrocode** [comment] 2021-05-13 14:31
The issue is that the registry ingests the markdown and has no context of relative path links like `examples/complete` and `test`.

https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/7e5a1047401c084ae6fc85cfae3ce52069852a98/README.yaml#L62-L64

This issue is probably across all of the cloudposse repos. IMO, it should be fixed in hashicorp's terraform registry, but we could also turn each link from a relative link

```
[examples/complete](examples/complete)
```

to an absolute link...

```
[examples/complete](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/tree/master/examples/complete)
```

but might be more trouble than it's worth.

**Closed** 2022-06-01 21:29 UTC
Labels: bug
